version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: notification_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: notifications_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d notifications_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: notification_api
    tty: true
    ports:
      - "5000:8080"
    environment:
      # Database Settings
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: user123
      DB_NAME: notifications_db
      PORT: 8080
      # RabbitMQ Settings (This is the missing link!)
      MQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: notification_consumer
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: user123
      DB_NAME: notifications_db
      MQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always

    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: notification_mq
    ports:
      - "5672:5672"   # The port for the code to talk to
      - "15672:15672" # The port for the visual dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data: