version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: notification_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notifications_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "app_user", "-papp_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: notification_api
    tty: true
    ports:
      - "5000:8080"
    environment:
      # Database Settings
      DB_HOST: mysql
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: notifications_db
      PORT: 8080
      # RabbitMQ Settings
      MQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: notification_consumer
    environment:
      DB_HOST: mysql
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: notifications_db
      MQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: notification_mq
    ports:
      - "5672:5672"   # The port for the code to talk to
      - "15672:15672" # The port for the visual dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  mysql_data: